
class TextUtil{
  static const politicas = "  "
      "1. Preámbulo "
      "\n"
      "La privacidad de sus datos es nuestra mayor preocupación y nos dedicamos a cumplir con la normativa de protección de datos personales."
      "\n"
      "Lea nuestra Privacidad de datos, cuyo objetivo es presentar la forma en que se procesan sus datos cuando utiliza la aplicación Mapstr y cómo puede ejercer sus derechos."
      "2. ¿Por qué tratamos sus datos?"
      "Procesamos sus datos personales para permitirle el uso completo de la aplicación Mapstr y su gama de funcionalidades."
      "Esencialmente, estamos tratando sus datos:"
      " para que pueda crear una cuenta de usuario de Descubre tizimin;"
      "para que guardes los lugares de tu interés;"
      "para que puedas crear etiquetas en el mapa digital proporcionado por 'Desc';"
      "para que puedas agregar a tus amigos y compartir ubicaciones con ellos;"
      " conocer la ubicación de su última conexión para garantizar la seguridad de su cuenta;"
      " para responder tu pregunta;"
      " para proporcionarle ofertas y noticias sobre la aplicación Mapstr;"
      "para mejorar nuestro servicio;"
      "para realizar estadísticas."
      "\n"
      "3. ¿Cuál es la base legal para el procesamiento?"
      "El procesamiento implementado se basa esencialmente en la relación contractual entre usted y nosotros luego de su aceptación de nuestros términos y condiciones generales de la aplicación Mapstr al crear una cuenta por primera vez. En algunos casos, la base legal también puede ser nuestro interés legítimo."
      "Recopilamos el mínimo de datos necesarios para permitirle utilizar todas las funcionalidades de la aplicación Descubre tizimin:"
      "su nombre, apellido, posiblemente su nombre de usuario de Facebook, su foto de perfil, su idioma y país para la gestión de su cuenta y perfil;"
      "su número de teléfono y sus contactos (libreta de direcciones) para que pueda encontrar amigos fácilmente en la aplicación. Los datos de su libreta de direcciones se codifican de forma segura y nunca se comparten con nadie;"
      "los datos de su aplicación (mapas, lugares, etiquetas, seguidores) para permitirle recuperar todo desde cualquier dispositivo que use;"
      "u ubicación de última conexión para detectar un cambio de ciudad y sugerirte contenido específico;"
      "Con fines analíticos y estadísticos, para garantizar que la aplicación funcione según lo previsto, podemos recopilar la ubicación de su dispositivo y la IP cuando se utiliza la aplicación."
      "\n"
      "6. ¿Quién es el destinatario de sus datos?"
      "No revendemos sus datos personales. El modelo de negocio de la aplicación 'Descubre tizimin' en ningún caso se basa en la venta de tus datos personales a terceros. Subrayamos que nuestros empleados están sujetos a un acuerdo de privacidad específico con respecto a sus datos."
      "Como ejemplo de dichos datos que podemos recopilar con fines analíticos, podemos recopilar y enviar a los destinatarios de datos anteriores: "
      "- Método de inicio de sesión"
      "\n"
      "7. ¿Cuánto tiempo se conservan sus datos?"
      " Sus datos se procesan por un período de tiempo limitado que definimos a la luz de las restricciones legales y contractuales y, en su defecto, de acuerdo con nuestras necesidades. Los principios son los siguientes:"
      "datos relativos a los usuarios: conservados durante la duración de las relaciones contractuales con nosotros, aumentados en 5 años según los requisitos legales;"
      "datos relativos a contactos y prospectos: conservados durante 3 años desde el último contacto del contacto o prospecto."
      "\n"
      "8. Sus derechos"
      "Tiene los siguientes derechos con respecto a sus datos personales:"
      "derecho a solicitarnos que confirmemos que sus datos se procesan, acceder a estos datos y solicitar una copia;"
      "derecho a obtener el borrado de sus datos si se opuso a su tratamiento con fines de prospección comercial o si decide borrar su cuenta 'Descubre tizimin';"
  "oponerse a cualquier elaboración de perfiles por nuestra parte;"
      "derecho a obtener la portabilidad de sus datos."
      " Tenga en cuenta que solo el usuario involucrado en el procesamiento puede ejercer los derechos previstos anteriormente."
      "En consecuencia, su solicitud deberá ir acompañada de una copia de un documento de identidad. En su defecto, su solicitud será denegada.";

  static const deleteData = "En concordancia con las regulaciones de Facebook para Apps y sitios web, debemos brindarle a los usuarios las instrucciones para eliminar sus datos. Si quieres eliminar tu actividad relacionada al Akaya App, lo puedes hacer de la siguiente manera."
      "\n"
      "1. Ingresa a tu cuenta de Facebook y haz clic en “Configuración y privacidad”. Después haz clic en “Configuración”."
      "\n"
      "2. Ve a la sección de “Apps y sitios web”, aquí podrás ver toda tu actividad relacionada a aplicaciones y páginas web registradas en tu cuenta de Facebook."
      "\n"
      "3. Selecciona la casilla correspondiente al Descubre Tizimin y haz clic en “Eliminar”."
      "\n"
      "4. Selecciona las casillas de acuerdo a tu preferencia y haz clic en “Eliminar”."
      "\n"
      "5. ¡Listo! Eliminaste a Descubre Tizimin App de tus actividades de manera exitosa. ";
}